config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  ActiveAdmin.routes(self)
  # get 'badges/index'
  # get 'badges/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :scenarios do
    resources :records, only: [:new, :create]
    resources :steps, only: [:index, :show]
  end

  resources :steps do
    resources :records, only: [:update]
  end
  resources :records, only: [:index, :edit]

  resources :badges, only: [:index, :create]

  get '/trial/steps/:id', to: 'steps#trial', as: 'trial'
  # get '/records/:id/badges', to: 'records#badges', as: 'badges'
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :scenario
  has_many :answers, dependent: :destroy

  has_one_attached :image
  has_one_attached :video
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :find_step, only: [:show, :trial]
  skip_before_action :authenticate_user!, only: [:trial]

  # def index
  #   @scenario = Scenario.find(params[:scenario_id])

  #   @c1 = Step.where(category: 1).first
  #   @c2 = Step.where(category: 2).first
  #   @c3 = Step.where(category: 3).first
  # end

  def show
    # This render the indivual Scenario Step page
    @scenario = @step.scenario
    @record = Record.new
    @my_record = Record.where(user_id: current_user.id, scenario_id: @scenario.id).last
    # Checking for current category
    case @step.category
    when 1
      @steps = Step.where(category: 1, scenario_id: @scenario.id).order(priority: :asc)
    when 2
      @steps = Step.where(category: 2, scenario_id: @scenario.id).order(priority: :asc)
    when 3
      @steps = Step.where(category: 3, scenario_id: @scenario.id).order(priority: :asc)
    end
  end

  def trial
    @scenario = @step.scenario
    case @step.category
    when 1
      @steps = Step.where(category: 1, scenario_id: @scenario.id).order(priority: :asc)
    when 2
      @steps = Step.where(category: 2, scenario_id: @scenario.id).order(priority: :asc)
    when 3
      @steps = Step.where(category: 3, scenario_id: @scenario.id).order(priority: :asc)
    end
  end

  private

  def find_step
    @step = Step.find(params[:id])
  end

  def step_params
    params.require(:step).permit(:category)
  end
end

app/views/steps/_demo.html.erb
<% step = @steps.first %>

<%= video_tag url_for(step.video), controls: true, class: "video-demo" %>
<div class="overlay invisible container d-flex justify-content-center align-items-center">
  <%=simple_form_for(@record, method: :patch, url: step_record_path(params[:id])) do |f| %>
    <%= f.submit "分步引导", class: "button-green invisible" %>
  <% end %>
</div>
<%= javascript_pack_tag 'video-demo' %>

app/views/steps/_quiz.html.erb
<!-- Quiz content -->
<div class="container my-5" id="quiz-content">
  <h5 class="text-primary">练习 <%= @step.priority %></h5>
  <!-- display the question -->
  <p class="my-3"><%= @steps.find_by_priority(@step.priority).question %> （选择正确答案的数字编号）</p>
  <p class="d-none" id="right-answer"><%= @step.right_answer %></p>
</div>

<!-- Quiz options -->
<div class="quiz-options d-flex justify-content-center align-items-center">
  <div class="options-container">
    <ul class="list-inline mb-0 d-flex justify-content-between">
      <li class="quiz-option-items list-inline-item">1</li>
      <li class="quiz-option-items list-inline-item">2</li>
      <li class="quiz-option-items list-inline-item">3</li>
    </ul>
  </div>
</div>
<div class="quiz-options-empty d-none"></div>

<!-- Incorrect answer alert -->
<div class="quiz-alert-incorrect d-none">
  <div class="container d-flex align-items-center" style="height: 100%;">
    <h6>再试一次</h6>
  </div>
</div>

<!-- Correct answer alert -->
<div class="quiz-alert-correct d-none">
  <div class="container d-flex justify-content-between align-items-center" style="height: 100%;">
    <h6>答对了！</h6>
    <!-- render the button according to progress -->
    <% if @steps.length == @step.priority %>
      <!-- since the last step of practice do not have next step,so here need to render a new page. Because the "完成啦" submit button contains the update action of record, so we put this part on views/records/edit.html.erb  -->
      <%= link_to "完成啦！", edit_record_path(@my_record, step_id: @step.id), class: "button-white" %>
    <% else %>
      <%= link_to "下一题", step_path(@step.id + 1), class: "button-white" %>
    <% end %>
  </div>
</div>
<div class="alert-empty d-none"></div>

<!-- Image -->
<div class="container my-3 text-center">
  <%= image_tag url_for(@steps.find_by_priority(@step.priority).image), style: "height: 100vh;"%>
</div>

<%= javascript_pack_tag 'quiz' %>

app/views/steps/_walkthrough.html.erb
<div class="d-flex justify-content-center" style="background-color: #595959;">
  <%= image_tag url_for(@steps.find_by_priority(@step.priority).image), class: "walkthrough-image" %>
</div>
<div class="fixed-bottom bg-success d-flex justify-content-center align-items-center" style="height: 72px;">
  <% if @steps.length == @step.priority %>
    <%=simple_form_for(@record, method: :patch, url: step_record_path(params[:id])) do |f| %>
      <%= f.submit "开始练习", class: "button-white" %>
    <% end %>
  <% else %>
    <%= link_to "下一步", step_path(@step.id + 1), class: "button-white" %>
  <% end %>
</div>

app/views/steps/index.html.erb
This page is just a placeholder page for Backend TESTING PURPOSES
<p><%#= link_to "demo", scenario_step_path(@scenario.id, @c1)%> </p>
<p><%#= link_to "walkthrough", scenario_step_path(@scenario.id, @c2)%> </p>
<p><%#= link_to "practice", scenario_step_path(@scenario.id, @c3)%> </p>
<!-- link to home placed temporarily placed here pending front-end integration -->
<p><%#= link_to "home", scenarios_path%> </p>
<p><%#= link_to "My Record", record_path(current_user)%> </p>

app/views/steps/show.html.erb
<%= link_to scenarios_path do %>
  <%= show_svg ("close-gray.svg")%>
<% end %>
<% step = @steps.first %>

<% case step.category %>
<% when 1 %>
  <%= render 'demo' %>
<% when 2 %>
  <%= render 'walkthrough' %>
<% when 3 %>
  <%= render 'quiz' %>
<% end %>

app/views/steps/trial.html.erb
<%= link_to scenarios_path do %>
  <%= show_svg ("close-gray.svg")%>
<% end %>
<% step = @steps.first %>
<% case step.category %>
<% when 1 %>
<%= video_tag url_for(step.video), controls: true, class: "video-demo" %>
<div class="overlay invisible container d-flex justify-content-center align-items-center">
  <%= link_to "分步引导", trial_path((@step.id + 1)), class: "button-green invisible" %>
</div>
<%= javascript_pack_tag 'video-demo' %>
<% when 2 %>
<!-- TODO: why is this tag at the top?? -->
<div class="d-flex justify-content-center" style="background-color: #595959;">
  <%= image_tag url_for(@steps.find_by_priority(@step.priority).image), class: "walkthrough-image" %>
</div>
<div class="fixed-bottom bg-success d-flex justify-content-center align-items-center" style="height: 72px;">
  <% if @steps.length == @step.priority %>
    <%= link_to "开始练习", trial_path((@step.id + 1)), class: "button-white" %>
  <% else %>
    <%= link_to "下一步", trial_path((@step.id + 1)), class: "button-white" %>
  <% end %>
</div>
<% when 3 %>
<!-- Quiz content -->
<div class="container my-5 px-4" id="quiz-content">
  <h5 class="text-primary">练习 <%= @step.priority %></h5>
  <!-- display the question -->
  <p class="my-3"><%= @steps.find_by_priority(@step.priority).question %> （选择正确答案的数字编号）</p>
  <p class="d-none" id="right-answer"><%= @step.right_answer %></p>
</div>
<!-- Quiz options -->
<div class="quiz-options d-flex justify-content-center align-items-center">
  <div class="options-container">
    <ul class="list-inline mb-0 d-flex justify-content-between">
      <li class="quiz-option-items list-inline-item">1</li>
      <li class="quiz-option-items list-inline-item">2</li>
      <li class="quiz-option-items list-inline-item">3</li>
    </ul>
  </div>
</div>
<div class="quiz-options-empty d-none"></div>
<!-- Incorrect answer alert -->
<div class="quiz-alert-incorrect d-none">
  <div class="container d-flex align-items-center" style="height: 100%;">
    <h6>再试一次</h6>
  </div>
</div>
<div class="quiz-alert-correct d-none">
  <div class="container d-flex justify-content-between align-items-center" style="height: 100%;">
    <h6>答对了！</h6>
    <!-- render the button according to progress -->
    <% if @steps.length == @step.priority %>
      <!-- since the last step of practice do not have next step,so here need to render a new page. Because the "完成啦" submit button contains the update action of record, so we put this part on views/records/edit.html.erb  -->
      <%= link_to "回首页", root_path, class: "button-white" %>
    <% else %>
      <%= link_to "下一题", trial_path((@step.id + 1)), class: "button-white" %>
    <% end %>
  </div>
</div>
<div class="alert-empty d-none"></div>
<!-- Image -->
<div class="container my-3 text-center">
  <%= image_tag url_for(@steps.find_by_priority(@step.priority).image), style: "height: 100vh;"%>
</div>
<%= javascript_pack_tag 'quiz' %>
<% end %>