config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  ActiveAdmin.routes(self)
  # get 'badges/index'
  # get 'badges/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :scenarios do
    resources :records, only: [:new, :create]
    resources :steps, only: [:index, :show]
  end

  resources :steps do
    resources :records, only: [:update]
  end
  resources :records, only: [:index, :edit]

  resources :badges, only: [:index, :create]

  get '/trial/steps/:id', to: 'steps#trial', as: 'trial'
  # get '/records/:id/badges', to: 'records#badges', as: 'badges'
end

app/models/scenario.rb
class Scenario < ApplicationRecord
  has_many :records, dependent: :destroy
  has_many :steps, dependent: :destroy
  has_one_attached :image

  def image_url
    if image.attachment.nil?
      return 'http://lorempixel.com/100/100'
    else
      return image.blob.service_url
    end
  end
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index,:show]

  before_action :find_scenario, only: [:show]

  def index
    @scenarios = Scenario.all.order(id: :asc)
  end

  def show
    # raise
    @record = Record.new
  end

  private

  def find_scenario
    @scenario = Scenario.find(params[:id])
  end
end

app/views/scenarios/index.html.erb
<!-- This is the overall scenarios listing landing page -->
<div class="container mt-3" style="padding-bottom: 72px;">
  <div class="row">
    <% @scenarios.each do |scenario| %>
      <div class="col-sm-12 col-md-6">
        <%= link_to scenario_path(scenario.id) do %>
          <div class="card scenario-card mb-3" style="background-image: url(<%= scenario.image_url %>)">
            <!-- example : callinf the language key from yml file -->
            <h5><%= t 'scenarios.index.welcome' %></h5>
            <h5><%#= scenario.title %></h5>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<%= javascript_pack_tag 'colored-cards' %>
<!-- Navbar -->
<ul class="nav nav-custom fixed-bottom">
  <div class="container d-flex justify-content-between align-items-center">
    <li class="nav-item">
      <%= link_to(scenarios_path, class: "nav-link active") do %>
        <%= image_tag "search-purple.svg", width: "24px" %>
        <p>首页</p>
      <% end %>
    </li>
    <li class="nav-item">
      <% if user_signed_in? %>
        <%= link_to(records_path(current_user), class: "nav-link") do %>
          <%= image_tag "marker-purple.svg", width: "24px" %>
          <p>记录</p>
        <% end %>
      <% else %>
        <%= link_to(new_user_session_path, class: "nav-link") do %>
          <%= image_tag "marker-purple.svg", width: "24px" %>
          <p>记录</p>
        <% end %>
      <% end %>
    </li>
    <li class="nav-item">
      <% if user_signed_in? %>
        <%= link_to(badges_path(current_user), class: "nav-link") do %>
          <%= image_tag "person-purple.svg", width: "24px" %>
          <p>我的</p>
        <% end %>
      <% else %>
        <%= link_to(new_user_session_path, class: "nav-link") do %>
          <%= image_tag "person-purple.svg", width: "24px" %>
          <p>我的</p>
        <% end %>
      <% end %>
    </li>
  </div>
</ul>

app/views/scenarios/show.html.erb
<div class="container my-5 px-5">
  <%= link_to scenarios_path do %>
    <%= show_svg ("close-gray.svg")%>
  <% end %>
  <!-- This page is to render the introduction page for the individual scenario -->
  <div class="py-2">
    <h3 class="text-primary"><%= @scenario.title %></h3>
    <div class="my-4">
      <p><%= @scenario.description %></p>
      <% if @scenario.description != "内容准备中......" %>
        <div>
          <h6 class="intro-index list-inline-item">1</h6>
          <h6 class="list-inline-item">短片</h6>
        </div>
        <div>
          <h6 class="intro-index list-inline-item">2</h6>
          <h6 class="list-inline-item">分步引导</h6>
        </div>
        <div>
          <h6 class="intro-index list-inline-item">3</h6>
          <h6 class="list-inline-item">练习</h6>
        </div>
      <% end %>
    </div>
    <% if !current_user && @scenario.title == "学会打车"%>
      <%= link_to "开始试用", trial_path(@scenario.steps.first), class: "btn btn-primary text-light btn-block mb-3" %>
    <% elsif @scenario.description == "内容准备中......" %>
      <%= link_to "回到首页", scenarios_path, class: "btn btn-primary text-light btn-block mb-3" %>
    <% else %>
      <%=simple_form_for(@record, method: :post, url: scenario_records_path(params[:id])) do |f| %>
        <%= f.submit "开始", class: "button-green btn-block mb-3"  %>
      <% end %>
    <% end %>
  </div>
</div>